apiVersion: ENC[AES256_GCM,data:4U8=,iv:xnXgeUKz70d8419SQe7GmT08n5huwEkGS9XO8uWR+fM=,tag:Gbe4Tsp5+EApx5OObADzPg==,type:str]
kind: ENC[AES256_GCM,data:S3Dgs7c6,iv:FctlvWg9HwQ4Ve4VC/vtmnpef4xbDUtWsx3awFdl1bU=,tag:CictznfSjxQzr7wBbm1ElQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4JI2k/3xZXwm/758zZkQYxBBVQE2,iv:Z56VUeR+gqTYOg1Q/cp6iYDz9ZQnxfAQZwzyhJ6AJZQ=,tag:AQA3dTNFLbuzLiFoBHpSWg==,type:str]
    namespace: ENC[AES256_GCM,data:HfDZfnwtE2Rx78G5HQ==,iv:1HfMvfULnxyFZpE2+3AX4z8W/V1M0C0FdeaTrs3wyK4=,tag:TgXvPgyjgECrCEHSHmTIkg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:0OaazkqNORyi,iv:SfvcCFs8HM937uCMemWCcOkvP1nXGwfngjuBoVPaZtw=,tag:2tOMgby5XAbNLbbtfQiypw==,type:str]
type: ENC[AES256_GCM,data:FNQIBdYi,iv:AGarKMbN4WlENj16sWr3OvEzjsPm8LW7vJiUpULPQe4=,tag:pfAgiDProQgY0xixzpvXrw==,type:str]
stringData:
    PLACEHOLDER: ENC[AES256_GCM,data:8yXOIqZ8//E=,iv:zJKPkbC/O9SYmVnKWjaTb3ZFNnMCYwMMs9N/G9iSe6o=,tag:rkUUAr+/S8pPraXH6ECWAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r5cjptkyd4wn82y5flfte4lm7y67nk2wxqhm7ncg5v23ea6seq9sfyjl0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUU0RMT1k4anYzUy9MdHpw
            ZUIrVkZlYTZhZVJ3YW1iL05XVFl5NlRSb2hZCi93cjYxbkc1YjQyZkVnVldhaFg1
            UjNHSjYyZ3BFVkErRTRPbXoyeXQ5NVkKLS0tIHBlYmcyYUUzVTlUTHpiOWtnd0xU
            LzJKeUNobWFmZkhlRUN6Slh2S1V5M2sKMOU2IwmNRg0zhC9L1O3uCRKtVo8hdIiV
            Z65GBujmy+S35Ysdccc//SO0jcswQ8au52Hh93uhocI2DRxokd58BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T04:29:55Z"
    mac: ENC[AES256_GCM,data:b384cIwR7juMugwB0yMEkIaUGuFjb6v7iKjRnW8G1Ocp2Qg587H2GOLeYTfMY95fTHF62Gg9fHkD/5DPZkWfHZY6H1GMBb3dexC85uSJanq2MWcYocyrjVmBibvEn4zwhHbcwUxFRiB7LmBeNZS0+jWA1p0BGtJ2lZBop/8uMBY=,iv:5i5ZnYG4XnFdr+T14e7G3rtzO59mWf5NYEi0UWEEsQQ=,tag:u3g7Yn+ne9YS92ci/mqusA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
